///
/// StatisticsFile.cs
/// CumulocityCoreLibrary
///
/// Copyright (c) 2014-2023 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
/// Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG.
///

using Com.Cumulocity.Client.Converter;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Runtime.Serialization;

namespace Com.Cumulocity.Client.Model 
{
	/// <summary> 
	/// Statistics file metadata. <br />
	/// </summary>
	///
	public class StatisticsFile 
	{
	
		/// <summary> 
		/// Unique identifier of the file. <br />
		/// </summary>
		///
		[JsonPropertyName("id")]
		public string? Id { get; set; }
	
		/// <summary> 
		/// Domain name where the statistics file come from. <br />
		/// </summary>
		///
		[JsonPropertyName("instanceName")]
		public string? InstanceName { get; set; }
	
		/// <summary> 
		/// File generation date. <br />
		/// </summary>
		///
		[JsonPropertyName("generationDate")]
		public System.DateTime? GenerationDate { get; set; }
	
		/// <summary> 
		/// Start date or date and time of the statistics attached in the file. <br />
		/// </summary>
		///
		[JsonPropertyName("dateFrom")]
		public System.DateTime? DateFrom { get; set; }
	
		/// <summary> 
		/// End date or date and time of the statistics attached in the file. <br />
		/// </summary>
		///
		[JsonPropertyName("dateTo")]
		public System.DateTime? DateTo { get; set; }
	
		/// <summary> 
		/// The type of statistics: <br />
		/// <list type="bullet">
		/// 	<item>
		/// 		<description>REAL - generated by the system on the first day of the month and including statistics from the previous month. <br />
		/// 		</description>
		/// 	</item>
		/// 	<item>
		/// 		<description>TEST - generated by the user with a time range specified in the query parameters (<c>dateFrom</c>, <c>dateTo</c>). <br />
		/// 		</description>
		/// 	</item>
		/// </list>
		/// </summary>
		///
		[JsonPropertyName("type")]
		public Type? PType { get; set; }
	
		/// <summary> 
		/// The type of statistics: <br />
		/// <list type="bullet">
		/// 	<item>
		/// 		<description>REAL - generated by the system on the first day of the month and including statistics from the previous month. <br />
		/// 		</description>
		/// 	</item>
		/// 	<item>
		/// 		<description>TEST - generated by the user with a time range specified in the query parameters (<c>dateFrom</c>, <c>dateTo</c>). <br />
		/// 		</description>
		/// 	</item>
		/// </list>
		/// </summary>
		///
		[JsonConverter(typeof(EnumConverterFactory))]
		public enum Type 
		{
			[EnumMember(Value = "REAL")]
			REAL,
			[EnumMember(Value = "TEST")]
			TEST
		}
	
	
		public override string ToString()
		{
			var jsonOptions = new JsonSerializerOptions() 
			{ 
				WriteIndented = true,
				DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
			};
			return JsonSerializer.Serialize(this, jsonOptions);
		}
	}
}
